blank_issues_enabled: false
contact_links:
  - name: 💬 Discussion
    url: https://github.com/Tamer7/fluxpilot/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/Tamer7/fluxpilot/blob/main/README.md
    about: Check the documentation for usage instructions 